Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: serverless-auth-pool
      Schema:
        - Name: email
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 6

  UserClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: user-pool-ui
      GenerateSecret: false
      UserPoolId: { Ref: UserPool }
      AccessTokenValidity: 5
      IdTokenValidity: 5
      ExplicitAuthFlows:
        - "ADMIN_NO_SRP_AUTH"